// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: cofee_shop.proto

package coffeeshop_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // e.g., "coffee", "tea", "pastries"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuRequest) Reset() {
	*x = MenuRequest{}
	mi := &file_cofee_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRequest) ProtoMessage() {}

func (x *MenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cofee_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRequest.ProtoReflect.Descriptor instead.
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return file_cofee_shop_proto_rawDescGZIP(), []int{0}
}

func (x *MenuRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type MenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // List of menu items
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuResponse) Reset() {
	*x = MenuResponse{}
	mi := &file_cofee_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResponse) ProtoMessage() {}

func (x *MenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cofee_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResponse.ProtoReflect.Descriptor instead.
func (*MenuResponse) Descriptor() ([]byte, []int) {
	return file_cofee_shop_proto_rawDescGZIP(), []int{1}
}

func (x *MenuResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_cofee_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_cofee_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_cofee_shop_proto_rawDescGZIP(), []int{2}
}

func (x *MenuItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerName  string                 `protobuf:"bytes,1,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"` // List of item names
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_cofee_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_cofee_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_cofee_shop_proto_rawDescGZIP(), []int{3}
}

func (x *Order) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Order) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Items         []string               `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"` // List of item names
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_cofee_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_cofee_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_cofee_shop_proto_rawDescGZIP(), []int{4}
}

func (x *Receipt) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Receipt) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Receipt) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Receipt) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type OrderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                    // e.g., "preparing", "ready", "delivered"
	EstimatedTime string                 `protobuf:"bytes,3,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"` // Estimated time for completion
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_cofee_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cofee_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_cofee_shop_proto_rawDescGZIP(), []int{5}
}

func (x *OrderStatus) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderStatus) GetEstimatedTime() string {
	if x != nil {
		return x.EstimatedTime
	}
	return ""
}

var File_cofee_shop_proto protoreflect.FileDescriptor

const file_cofee_shop_proto_rawDesc = "" +
	"\n" +
	"\x10cofee_shop.proto\x12\vcoffee_shop\")\n" +
	"\vMenuRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\";\n" +
	"\fMenuResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.coffee_shop.MenuItemR\x05items\"_\n" +
	"\bMenuItem\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"B\n" +
	"\x05order\x12#\n" +
	"\rcustomer_name\x18\x01 \x01(\tR\fcustomerName\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\"\x80\x01\n" +
	"\aReceipt\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12#\n" +
	"\rcustomer_name\x18\x02 \x01(\tR\fcustomerName\x12\x14\n" +
	"\x05items\x18\x03 \x03(\tR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\"g\n" +
	"\vOrderStatus\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0eestimated_time\x18\x03 \x01(\tR\restimatedTime2\xd1\x01\n" +
	"\x0fCoffeeShopNimar\x12@\n" +
	"\aGetMenu\x12\x18.coffee_shop.MenuRequest\x1a\x19.coffee_shop.MenuResponse\"\x00\x128\n" +
	"\n" +
	"PlaceOrder\x12\x12.coffee_shop.order\x1a\x14.coffee_shop.Receipt\"\x00\x12B\n" +
	"\x0eGetOrderStatus\x12\x14.coffee_shop.Receipt\x1a\x18.coffee_shop.OrderStatus\"\x00B\x15Z\x13./coffeeshop_protosb\x06proto3"

var (
	file_cofee_shop_proto_rawDescOnce sync.Once
	file_cofee_shop_proto_rawDescData []byte
)

func file_cofee_shop_proto_rawDescGZIP() []byte {
	file_cofee_shop_proto_rawDescOnce.Do(func() {
		file_cofee_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cofee_shop_proto_rawDesc), len(file_cofee_shop_proto_rawDesc)))
	})
	return file_cofee_shop_proto_rawDescData
}

var file_cofee_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cofee_shop_proto_goTypes = []any{
	(*MenuRequest)(nil),  // 0: coffee_shop.MenuRequest
	(*MenuResponse)(nil), // 1: coffee_shop.MenuResponse
	(*MenuItem)(nil),     // 2: coffee_shop.MenuItem
	(*Order)(nil),        // 3: coffee_shop.order
	(*Receipt)(nil),      // 4: coffee_shop.Receipt
	(*OrderStatus)(nil),  // 5: coffee_shop.OrderStatus
}
var file_cofee_shop_proto_depIdxs = []int32{
	2, // 0: coffee_shop.MenuResponse.items:type_name -> coffee_shop.MenuItem
	0, // 1: coffee_shop.CoffeeShopNimar.GetMenu:input_type -> coffee_shop.MenuRequest
	3, // 2: coffee_shop.CoffeeShopNimar.PlaceOrder:input_type -> coffee_shop.order
	4, // 3: coffee_shop.CoffeeShopNimar.GetOrderStatus:input_type -> coffee_shop.Receipt
	1, // 4: coffee_shop.CoffeeShopNimar.GetMenu:output_type -> coffee_shop.MenuResponse
	4, // 5: coffee_shop.CoffeeShopNimar.PlaceOrder:output_type -> coffee_shop.Receipt
	5, // 6: coffee_shop.CoffeeShopNimar.GetOrderStatus:output_type -> coffee_shop.OrderStatus
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cofee_shop_proto_init() }
func file_cofee_shop_proto_init() {
	if File_cofee_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cofee_shop_proto_rawDesc), len(file_cofee_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cofee_shop_proto_goTypes,
		DependencyIndexes: file_cofee_shop_proto_depIdxs,
		MessageInfos:      file_cofee_shop_proto_msgTypes,
	}.Build()
	File_cofee_shop_proto = out.File
	file_cofee_shop_proto_goTypes = nil
	file_cofee_shop_proto_depIdxs = nil
}
